name: ci
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup cpp
      uses: aminya/setup-cpp@v1
      with:
        compiler: llvm
        cmake: true

    - name: Install dependencies
      run: | 
        sudo apt-get update
        sudo apt-get clean 
        sudo apt-get install -y build-essential libzstd-dev libgtest-dev libgmock-dev
        sudo apt-get install binaryen
        sudo apt-get install nodejs -y

    - name: Create a symlink to cmake
      run: |
        mkdir -p /opt/cmake/bin
        ln -s $(which cmake) /opt/cmake/bin/cmake

    - name: Build and test
      run: |
        cmake -Bbuild -DTESTS=ON -DRUN_WASM_FILE_LOCATION="/home/runner/work/bird-lang/bird-lang/tests/helpers/run_wasm.js"
        make -C build
        ctest --test-dir build --verbose
